---
divband_unknown_domain: unknown.divband.com

divband_install_docker: true
divband_deploy_stack: true

divband_backup_dir: /etc/divband/backups
divband_ubuntu_sources_path: /etc/apt/sources.list.d/ubuntu.sources
divband_ubuntu_sources_backup: /etc/divband/backups/ubuntu.sources.original
divband_hosts_backup: /etc/divband/backups/hosts.original

divband_arvan_hosts:
  - ip: 185.143.232.201
    names:
      - mirror.arvancloud.ir
      - docker.arvancloud.ir
  - ip: 185.143.232.253
    names:
      - mirror.arvancloud.ir
      - docker.arvancloud.ir

divband_arvan_docker_packages:
  - docker.io=24.0.7-0ubuntu4
  - docker-compose-v2=2.24.6+ds1-0ubuntu2
  - containerd=1.7.12-0ubuntu4
  - runc=1.1.12-0ubuntu3

divband_default_docker_packages:
  - docker.io
  - docker-compose-v2
  - containerd
  - runc
