---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - divband_install_docker | bool
    - ansible_facts.os_family == "Debian"

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ divband_default_docker_packages }}"
    state: present
  when:
    - divband_install_docker | bool
    - ansible_facts.os_family == "Debian"

- name: Enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  when: divband_install_docker | bool
