---
cluster_registry_namespace: divband-registry
cluster_registry_name: divband-registry
cluster_registry_image: registry:2
cluster_registry_storage_size: 10Gi
cluster_registry_service_port: 5000
cluster_registry_node_port: 30500
cluster_registry_host: localhost
cluster_registry_endpoint: "{{ cluster_registry_host }}:{{ cluster_registry_node_port }}"
cluster_registry_k3s_endpoint: "http://127.0.0.1:{{ cluster_registry_node_port }}"
cluster_registry_registries_path: /etc/rancher/k3s/registries.yaml
