apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-secrets
  namespace: project-REPLACE_WITH_SLUG
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/project-slug: REPLACE_WITH_SLUG
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: REPLACE_WITH_CLUSTER_SECRET_STORE
  target:
    name: project-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          divband.io/project-id: REPLACE_WITH_PROJECT_ID
          divband.io/project-slug: REPLACE_WITH_SLUG
  dataFrom:
    - extract:
        key: projects/REPLACE_WITH_PROJECT_ID/REPLACE_WITH_ENVIRONMENT
