apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-web
  namespace: REPLACE_WITH_NAMESPACE
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/project-slug: REPLACE_WITH_SLUG
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
  annotations:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
spec:
  parentRefs:
    - name: REPLACE_WITH_GATEWAY_NAME
      namespace: REPLACE_WITH_GATEWAY_NAMESPACE
      sectionName: https
  hostnames:
    - REPLACE_WITH_SLUG.divband.ir
    - REPLACE_WITH_VERIFIED_CUSTOM_DOMAIN
  rules:
    - backendRefs:
        - name: REPLACE_WITH_PUBLIC_SERVICE_NAME
          port: REPLACE_WITH_PUBLIC_SERVICE_PORT
