apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-web
  namespace: REPLACE_WITH_NAMESPACE
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/project-slug: REPLACE_WITH_SLUG
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
  annotations:
    cert-manager.io/cluster-issuer: REPLACE_WITH_CLUSTER_ISSUER
    external-dns.alpha.kubernetes.io/hostname: REPLACE_WITH_PLATFORM_HOSTNAME,REPLACE_WITH_WORKSPACE_HOSTNAME
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
spec:
  ingressClassName: REPLACE_WITH_INGRESS_CLASS
  tls:
    - secretName: public-web-tls
      hosts:
        - REPLACE_WITH_PLATFORM_HOSTNAME
        - REPLACE_WITH_WORKSPACE_HOSTNAME
  rules:
    - host: REPLACE_WITH_PLATFORM_HOSTNAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: REPLACE_WITH_PUBLIC_SERVICE_NAME
                port:
                  number: REPLACE_WITH_PUBLIC_SERVICE_PORT
    - host: REPLACE_WITH_WORKSPACE_HOSTNAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workspace-REPLACE_WITH_SLUG
                port:
                  number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-web
  namespace: REPLACE_WITH_NAMESPACE
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
  annotations:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
spec:
  secretName: public-web-tls
  issuerRef:
    kind: ClusterIssuer
    name: REPLACE_WITH_CLUSTER_ISSUER
  dnsNames:
    - REPLACE_WITH_PLATFORM_HOSTNAME
    - REPLACE_WITH_WORKSPACE_HOSTNAME
