apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-deployer
  namespace: project-REPLACE_WITH_SLUG
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/project-slug: REPLACE_WITH_SLUG
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-deployer
  namespace: project-REPLACE_WITH_SLUG
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
rules:
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets']
    verbs: ['get', 'list', 'watch', 'create', 'patch', 'update']
  - apiGroups: ['']
    resources: ['configmaps', 'services']
    verbs: ['get', 'list', 'watch', 'create', 'patch', 'update']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses']
    verbs: ['get', 'list', 'watch', 'create', 'patch', 'update']
  - apiGroups: ['cert-manager.io']
    resources: ['certificates']
    verbs: ['get', 'list', 'watch', 'create', 'patch', 'update']
  - apiGroups: ['external-secrets.io']
    resources: ['externalsecrets']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-deployer
  namespace: project-REPLACE_WITH_SLUG
  labels:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
subjects:
  - kind: ServiceAccount
    name: project-deployer
    namespace: project-REPLACE_WITH_SLUG
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-deployer
