apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: project-REPLACE_WITH_SLUG
  labels:
    app.kubernetes.io/name: static-site
    app.kubernetes.io/component: static-site
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/project-slug: REPLACE_WITH_SLUG
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
  annotations:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
spec:
  replicas: REPLACE_WITH_STATIC_REPLICAS
  selector:
    matchLabels:
      app.kubernetes.io/name: static-site
      divband.io/project-id: REPLACE_WITH_PROJECT_ID
  template:
    metadata:
      labels:
        app.kubernetes.io/name: static-site
        app.kubernetes.io/component: static-site
        divband.io/project-id: REPLACE_WITH_PROJECT_ID
        divband.io/project-slug: REPLACE_WITH_SLUG
        divband.io/expose: public
        divband.io/tenant-id: REPLACE_WITH_TENANT_ID
        divband.io/environment: REPLACE_WITH_ENVIRONMENT
        divband.io/owner-id: REPLACE_WITH_OWNER_ID
      annotations:
        divband.io/project-id: REPLACE_WITH_PROJECT_ID
        divband.io/tenant-id: REPLACE_WITH_TENANT_ID
        divband.io/environment: REPLACE_WITH_ENVIRONMENT
        divband.io/owner-id: REPLACE_WITH_OWNER_ID
    spec:
      serviceAccountName: project-deployer
      containers:
        - name: static-site
          image: REPLACE_WITH_STATIC_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: REPLACE_WITH_STATIC_CPU_REQUEST
              memory: REPLACE_WITH_STATIC_MEMORY_REQUEST
            limits:
              cpu: REPLACE_WITH_STATIC_CPU_LIMIT
              memory: REPLACE_WITH_STATIC_MEMORY_LIMIT
---
apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: project-REPLACE_WITH_SLUG
  labels:
    app.kubernetes.io/name: static-site
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
  annotations:
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
    divband.io/tenant-id: REPLACE_WITH_TENANT_ID
    divband.io/environment: REPLACE_WITH_ENVIRONMENT
    divband.io/owner-id: REPLACE_WITH_OWNER_ID
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: static-site
    divband.io/project-id: REPLACE_WITH_PROJECT_ID
  ports:
    - name: http
      port: 80
      targetPort: http
