---
kubernetes_distribution: k3s
kubernetes_node_role: worker
kubernetes_api_endpoint: "https://127.0.0.1:6443"
kubernetes_pod_cidr: 10.42.0.0/16
kubernetes_service_cidr: 10.43.0.0/16
kubernetes_k3s_channel: stable
kubernetes_k3s_install_url: https://get.k3s.io
kubernetes_k3s_resolv_conf: ""
kubernetes_join_token: "{{ vault_kubernetes_join_token | default('REPLACE_WITH_K3S_JOIN_TOKEN') }}"
kubernetes_disable_builtin_ingress: true
kubernetes_kubeconfig_remote_path: /etc/rancher/k3s/k3s.yaml
kubernetes_kubeconfig_export_path: /etc/rancher/k3s/divband-kubeconfig.yaml
kubernetes_kubeconfig_local_path: "{{ playbook_dir }}/../artifacts/kubeconfig"
kubernetes_kubeconfig_context: divband-{{ divband_environment | default('production') }}
