---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload ufw
  ansible.builtin.command:
    cmd: ufw reload

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
